### ISSUE TITLE
Migration failing

### ISSUE THREAD

**Issue by fnyamweya** [JSLancerTeam/saasgear#84]
When I clone the master branch and do the initial setup, I am unable to run the initial migration to create the tables

I get the error below when I run `npm run db:migrate`

Node Version: `v14`
OS: Ubuntu `22.04`

```Error: No configuration file found and no commandline connection parameters passed
    at mkConfigObj (/saasgear/api/node_modules/knex/bin/utils/cli-config-utils.js:11:11)
    at initKnex (/saasgear/api/node_modules/knex/bin/cli.js:48:7)
    at Command.<anonymous> (/saasgear/api/node_modules/knex/bin/cli.js:170:32)
    at Command.listener [as _actionHandler] (/saasgear/api/node_modules/knex/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/saasgear/api/node_modules/knex/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/saasgear/api/node_modules/knex/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/saasgear/api/node_modules/knex/node_modules/commander/index.js:970:12)
    at Command.parse (/saasgear/api/node_modules/knex/node_modules/commander/index.js:801:10)
    at Liftoff.invoke (/saasgear/api/node_modules/knex/bin/cli.js:354:13)
    at Liftoff.execute (/saasgear/api/node_modules/liftoff/index.js:201:12)```

**Comment by davidtran** [comment]
hi @fnyamweya  do you have .env file?

**Comment by raviadi12** [comment]
Hi, i've got same problem too! I've solved it by converting the files written in Typescript to Javascript. All the files that needs to be convert from Typescript to Javascript are in the directory : "api/config" and "api/migrations". Be sure to only duplicate the files not replaced it as you will need it later. After did that, change the extension of the converted files to whatever it is except .js to prevent clashing with the Typescript files. You can use any online tools to change from Typescript to Javascript. Sorry if my grammar is bad.

**Comment by davidtran** [comment]
hi @raviadi12 @fnyamweya I have pushed fix for the migration issue. Could you please test it?
